//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:23:30 PM PDT 
//


package _int.iho.s100.csl._5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * An extent in time.
 * 
 * <p>Java class for S100_TM_Period complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S100_TM_Period"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="closure" type="{http://www.iho.int/s100/csl/5.0}S100_IntervalType"/&gt;
 *         &lt;element name="begin" type="{http://www.iho.int/s100/csl/5.0}S100_TM_Instant"/&gt;
 *         &lt;element name="end" type="{http://www.iho.int/s100/csl/5.0}S100_TM_Instant"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S100_TM_Period", propOrder = {
    "closure",
    "begin",
    "end"
})
public class S100TMPeriod {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected S100IntervalType closure;
    @XmlElement(required = true)
    protected S100TMInstant begin;
    @XmlElement(required = true)
    protected S100TMInstant end;

    /**
     * Gets the value of the closure property.
     * 
     * @return
     *     possible object is
     *     {@link S100IntervalType }
     *     
     */
    public S100IntervalType getClosure() {
        return closure;
    }

    /**
     * Sets the value of the closure property.
     * 
     * @param value
     *     allowed object is
     *     {@link S100IntervalType }
     *     
     */
    public void setClosure(S100IntervalType value) {
        this.closure = value;
    }

    /**
     * Gets the value of the begin property.
     * 
     * @return
     *     possible object is
     *     {@link S100TMInstant }
     *     
     */
    public S100TMInstant getBegin() {
        return begin;
    }

    /**
     * Sets the value of the begin property.
     * 
     * @param value
     *     allowed object is
     *     {@link S100TMInstant }
     *     
     */
    public void setBegin(S100TMInstant value) {
        this.begin = value;
    }

    /**
     * Gets the value of the end property.
     * 
     * @return
     *     possible object is
     *     {@link S100TMInstant }
     *     
     */
    public S100TMInstant getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     * @param value
     *     allowed object is
     *     {@link S100TMInstant }
     *     
     */
    public void setEnd(S100TMInstant value) {
        this.end = value;
    }

}
