//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:26:08 PM PDT 
//


package _int.iho.s100.ic._5;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the _int.iho.s100.ic._5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _S100ICInteroperabilityCatalogue_QNAME = new QName("http://www.iho.int/S100/IC/5.0", "S100_IC_InteroperabilityCatalogue");
    private final static QName _S100DigitalSignatureValueSignedPublicKey_QNAME = new QName("", "signedPublicKey");
    private final static QName _S100DigitalSignatureValueDigitalSignature_QNAME = new QName("", "digitalSignature");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: _int.iho.s100.ic._5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link S100ICDisplayPlane }
     * 
     */
    public S100ICDisplayPlane createS100ICDisplayPlane() {
        return new S100ICDisplayPlane();
    }

    /**
     * Create an instance of {@link S100DigitalSignatureValue }
     * 
     */
    public S100DigitalSignatureValue createS100DigitalSignatureValue() {
        return new S100DigitalSignatureValue();
    }

    /**
     * Create an instance of {@link S100ICPredefinedCombination }
     * 
     */
    public S100ICPredefinedCombination createS100ICPredefinedCombination() {
        return new S100ICPredefinedCombination();
    }

    /**
     * Create an instance of {@link S100ICInteroperabilityCatalogue }
     * 
     */
    public S100ICInteroperabilityCatalogue createS100ICInteroperabilityCatalogue() {
        return new S100ICInteroperabilityCatalogue();
    }

    /**
     * Create an instance of {@link S100ICFeature }
     * 
     */
    public S100ICFeature createS100ICFeature() {
        return new S100ICFeature();
    }

    /**
     * Create an instance of {@link S100ICDrawingInstruction }
     * 
     */
    public S100ICDrawingInstruction createS100ICDrawingInstruction() {
        return new S100ICDrawingInstruction();
    }

    /**
     * Create an instance of {@link DataProduct }
     * 
     */
    public DataProduct createDataProduct() {
        return new DataProduct();
    }

    /**
     * Create an instance of {@link S100ICSuppressedFeatureLayer }
     * 
     */
    public S100ICSuppressedFeatureLayer createS100ICSuppressedFeatureLayer() {
        return new S100ICSuppressedFeatureLayer();
    }

    /**
     * Create an instance of {@link S100ICSimpleRule }
     * 
     */
    public S100ICSimpleRule createS100ICSimpleRule() {
        return new S100ICSimpleRule();
    }

    /**
     * Create an instance of {@link S100ICHybridFeature }
     * 
     */
    public S100ICHybridFeature createS100ICHybridFeature() {
        return new S100ICHybridFeature();
    }

    /**
     * Create an instance of {@link S100ICSuppressedFeatureInstance }
     * 
     */
    public S100ICSuppressedFeatureInstance createS100ICSuppressedFeatureInstance() {
        return new S100ICSuppressedFeatureInstance();
    }

    /**
     * Create an instance of {@link S100ICThematicRule }
     * 
     */
    public S100ICThematicRule createS100ICThematicRule() {
        return new S100ICThematicRule();
    }

    /**
     * Create an instance of {@link S100ICCompleteRule }
     * 
     */
    public S100ICCompleteRule createS100ICCompleteRule() {
        return new S100ICCompleteRule();
    }

    /**
     * Create an instance of {@link S100ICDisplayPlane.Features }
     * 
     */
    public S100ICDisplayPlane.Features createS100ICDisplayPlaneFeatures() {
        return new S100ICDisplayPlane.Features();
    }

    /**
     * Create an instance of {@link S100ICDisplayPlane.DrawingInstructions }
     * 
     */
    public S100ICDisplayPlane.DrawingInstructions createS100ICDisplayPlaneDrawingInstructions() {
        return new S100ICDisplayPlane.DrawingInstructions();
    }

    /**
     * Create an instance of {@link S100DigitalSignatureValue.SignedPublicKey }
     * 
     */
    public S100DigitalSignatureValue.SignedPublicKey createS100DigitalSignatureValueSignedPublicKey() {
        return new S100DigitalSignatureValue.SignedPublicKey();
    }

    /**
     * Create an instance of {@link S100ICPredefinedCombination.SuppressedFeatureLayers }
     * 
     */
    public S100ICPredefinedCombination.SuppressedFeatureLayers createS100ICPredefinedCombinationSuppressedFeatureLayers() {
        return new S100ICPredefinedCombination.SuppressedFeatureLayers();
    }

    /**
     * Create an instance of {@link S100ICPredefinedCombination.DerivedFeatures }
     * 
     */
    public S100ICPredefinedCombination.DerivedFeatures createS100ICPredefinedCombinationDerivedFeatures() {
        return new S100ICPredefinedCombination.DerivedFeatures();
    }

    /**
     * Create an instance of {@link S100ICInteroperabilityCatalogue.DisplayPlanes }
     * 
     */
    public S100ICInteroperabilityCatalogue.DisplayPlanes createS100ICInteroperabilityCatalogueDisplayPlanes() {
        return new S100ICInteroperabilityCatalogue.DisplayPlanes();
    }

    /**
     * Create an instance of {@link S100ICInteroperabilityCatalogue.PredefinedProductCombinations }
     * 
     */
    public S100ICInteroperabilityCatalogue.PredefinedProductCombinations createS100ICInteroperabilityCataloguePredefinedProductCombinations() {
        return new S100ICInteroperabilityCatalogue.PredefinedProductCombinations();
    }

    /**
     * Create an instance of {@link S100ICInteroperabilityCatalogue.HybridizationRules }
     * 
     */
    public S100ICInteroperabilityCatalogue.HybridizationRules createS100ICInteroperabilityCatalogueHybridizationRules() {
        return new S100ICInteroperabilityCatalogue.HybridizationRules();
    }

    /**
     * Create an instance of {@link S100ICInteroperabilityCatalogue.HybridPC }
     * 
     */
    public S100ICInteroperabilityCatalogue.HybridPC createS100ICInteroperabilityCatalogueHybridPC() {
        return new S100ICInteroperabilityCatalogue.HybridPC();
    }

    /**
     * Create an instance of {@link S100ICInteroperabilityCatalogue.HybridFC }
     * 
     */
    public S100ICInteroperabilityCatalogue.HybridFC createS100ICInteroperabilityCatalogueHybridFC() {
        return new S100ICInteroperabilityCatalogue.HybridFC();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link S100ICInteroperabilityCatalogue }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link S100ICInteroperabilityCatalogue }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.iho.int/S100/IC/5.0", name = "S100_IC_InteroperabilityCatalogue", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/cat/1.0", substitutionHeadName = "AbstractCT_Catalogue")
    public JAXBElement<S100ICInteroperabilityCatalogue> createS100ICInteroperabilityCatalogue(S100ICInteroperabilityCatalogue value) {
        return new JAXBElement<S100ICInteroperabilityCatalogue>(_S100ICInteroperabilityCatalogue_QNAME, S100ICInteroperabilityCatalogue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link S100DigitalSignatureValue.SignedPublicKey }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link S100DigitalSignatureValue.SignedPublicKey }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "signedPublicKey", scope = S100DigitalSignatureValue.class)
    public JAXBElement<S100DigitalSignatureValue.SignedPublicKey> createS100DigitalSignatureValueSignedPublicKey(S100DigitalSignatureValue.SignedPublicKey value) {
        return new JAXBElement<S100DigitalSignatureValue.SignedPublicKey>(_S100DigitalSignatureValueSignedPublicKey_QNAME, S100DigitalSignatureValue.SignedPublicKey.class, S100DigitalSignatureValue.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "", name = "digitalSignature", scope = S100DigitalSignatureValue.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    public JAXBElement<byte[]> createS100DigitalSignatureValueDigitalSignature(byte[] value) {
        return new JAXBElement<byte[]>(_S100DigitalSignatureValueDigitalSignature_QNAME, byte[].class, S100DigitalSignatureValue.class, ((byte[]) value));
    }

}
