//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:26:08 PM PDT 
//


package _int.iho.s100.ic._5;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Describes operations for suppressing all instances of a feature type in one product by features from another product.
 * 
 * <p>Java class for S100_IC_SuppressedFeatureLayer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S100_IC_SuppressedFeatureLayer"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="identifier" type="{http://www.iho.int/S100/IC/5.0}GenericIDType"/&gt;
 *         &lt;element name="featureCode" type="{http://www.iho.int/S100/IC/5.0}FeatureCodeType"/&gt;
 *         &lt;element name="product" type="{http://www.iho.int/S100/IC/5.0}dataProduct"/&gt;
 *         &lt;element name="featureRef" type="{http://www.iho.int/S100/IC/5.0}GenericIDType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="drawingInstructionRef" type="{http://www.iho.int/S100/IC/5.0}GenericIDType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S100_IC_SuppressedFeatureLayer", propOrder = {
    "identifier",
    "featureCode",
    "product",
    "featureRef",
    "drawingInstructionRef"
})
public class S100ICSuppressedFeatureLayer {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String identifier;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String featureCode;
    @XmlElement(required = true)
    protected DataProduct product;
    @XmlSchemaType(name = "anyURI")
    protected List<String> featureRef;
    @XmlSchemaType(name = "anyURI")
    protected List<String> drawingInstructionRef;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the featureCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureCode() {
        return featureCode;
    }

    /**
     * Sets the value of the featureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureCode(String value) {
        this.featureCode = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link DataProduct }
     *     
     */
    public DataProduct getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataProduct }
     *     
     */
    public void setProduct(DataProduct value) {
        this.product = value;
    }

    /**
     * Gets the value of the featureRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the featureRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeatureRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFeatureRef() {
        if (featureRef == null) {
            featureRef = new ArrayList<String>();
        }
        return this.featureRef;
    }

    /**
     * Gets the value of the drawingInstructionRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the drawingInstructionRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDrawingInstructionRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDrawingInstructionRef() {
        if (drawingInstructionRef == null) {
            drawingInstructionRef = new ArrayList<String>();
        }
        return this.drawingInstructionRef;
    }

}
