//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:26:08 PM PDT 
//


package _int.iho.s100.ic._5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Rule describing how a set of feature instances is combined to create a hybrid feature type.Thematic rules may operate on only thematic attributes. The input features are required to have spatially equal geometry within a tolerance set by the system.
 * 
 * <p>Java class for S100_IC_ThematicRule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S100_IC_ThematicRule"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.iho.int/S100/IC/5.0}S100_IC_HybridFeatureCreationRule"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S100_IC_ThematicRule")
public class S100ICThematicRule
    extends S100ICHybridFeatureCreationRule
{


}
