//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:26:08 PM PDT 
//


package _int.iho.s100.ic._5;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.iso.standards.iso._19115.__3.cat._1.AbstractCTCatalogueType;


/**
 * An interoperability catalogue contains operations and rules for the interoperation of a set of S-100-based data products.
 * 
 * <p>Java class for S100_IC_InteroperabilityCatalogue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S100_IC_InteroperabilityCatalogue"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://standards.iso.org/iso/19115/-3/cat/1.0}AbstractCT_Catalogue_Type"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="interoperabilityLevel" type="{http://www.iho.int/S100/IC/5.0}interoperabilityLevelType" minOccurs="0"/&gt;
 *         &lt;element name="requirementType" type="{http://www.iho.int/S100/IC/5.0}requirementType"/&gt;
 *         &lt;element name="requirementDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="productCovered" type="{http://www.iho.int/S100/IC/5.0}dataProduct" maxOccurs="unbounded" minOccurs="2"/&gt;
 *         &lt;element name="displayPlanes"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="S100_IC_DisplayPlane" type="{http://www.iho.int/S100/IC/5.0}S100_IC_DisplayPlane" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="predefinedProductCombinations" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="S100_IC_PredefinedCombination" type="{http://www.iho.int/S100/IC/5.0}S100_IC_PredefinedCombination" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="hybridizationRules" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="S100_IC_SimpleRule" type="{http://www.iho.int/S100/IC/5.0}S100_IC_SimpleRule" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="S100_IC_ThematicRule" type="{http://www.iho.int/S100/IC/5.0}S100_IC_ThematicRule" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="S100_IC_CompleteRule" type="{http://www.iho.int/S100/IC/5.0}S100_IC_CompleteRule" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="hybridPC" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="S100_IC_HybridPC" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="hybridFC" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="S100_IC_HybridFC" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S100_IC_InteroperabilityCatalogue", propOrder = {
    "description",
    "comment",
    "interoperabilityLevel",
    "requirementType",
    "requirementDescription",
    "productCovered",
    "displayPlanes",
    "predefinedProductCombinations",
    "hybridizationRules",
    "hybridPC",
    "hybridFC"
})
public class S100ICInteroperabilityCatalogue
    extends AbstractCTCatalogueType
{

    @XmlElement(required = true)
    protected String description;
    protected String comment;
    protected Integer interoperabilityLevel;
    @XmlElement(required = true)
    protected String requirementType;
    protected String requirementDescription;
    @XmlElement(required = true)
    protected List<DataProduct> productCovered;
    @XmlElement(required = true)
    protected S100ICInteroperabilityCatalogue.DisplayPlanes displayPlanes;
    protected S100ICInteroperabilityCatalogue.PredefinedProductCombinations predefinedProductCombinations;
    protected S100ICInteroperabilityCatalogue.HybridizationRules hybridizationRules;
    protected List<S100ICInteroperabilityCatalogue.HybridPC> hybridPC;
    protected List<S100ICInteroperabilityCatalogue.HybridFC> hybridFC;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the interoperabilityLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInteroperabilityLevel() {
        return interoperabilityLevel;
    }

    /**
     * Sets the value of the interoperabilityLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInteroperabilityLevel(Integer value) {
        this.interoperabilityLevel = value;
    }

    /**
     * Gets the value of the requirementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequirementType() {
        return requirementType;
    }

    /**
     * Sets the value of the requirementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequirementType(String value) {
        this.requirementType = value;
    }

    /**
     * Gets the value of the requirementDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequirementDescription() {
        return requirementDescription;
    }

    /**
     * Sets the value of the requirementDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequirementDescription(String value) {
        this.requirementDescription = value;
    }

    /**
     * Gets the value of the productCovered property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productCovered property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductCovered().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataProduct }
     * 
     * 
     */
    public List<DataProduct> getProductCovered() {
        if (productCovered == null) {
            productCovered = new ArrayList<DataProduct>();
        }
        return this.productCovered;
    }

    /**
     * Gets the value of the displayPlanes property.
     * 
     * @return
     *     possible object is
     *     {@link S100ICInteroperabilityCatalogue.DisplayPlanes }
     *     
     */
    public S100ICInteroperabilityCatalogue.DisplayPlanes getDisplayPlanes() {
        return displayPlanes;
    }

    /**
     * Sets the value of the displayPlanes property.
     * 
     * @param value
     *     allowed object is
     *     {@link S100ICInteroperabilityCatalogue.DisplayPlanes }
     *     
     */
    public void setDisplayPlanes(S100ICInteroperabilityCatalogue.DisplayPlanes value) {
        this.displayPlanes = value;
    }

    /**
     * Gets the value of the predefinedProductCombinations property.
     * 
     * @return
     *     possible object is
     *     {@link S100ICInteroperabilityCatalogue.PredefinedProductCombinations }
     *     
     */
    public S100ICInteroperabilityCatalogue.PredefinedProductCombinations getPredefinedProductCombinations() {
        return predefinedProductCombinations;
    }

    /**
     * Sets the value of the predefinedProductCombinations property.
     * 
     * @param value
     *     allowed object is
     *     {@link S100ICInteroperabilityCatalogue.PredefinedProductCombinations }
     *     
     */
    public void setPredefinedProductCombinations(S100ICInteroperabilityCatalogue.PredefinedProductCombinations value) {
        this.predefinedProductCombinations = value;
    }

    /**
     * Gets the value of the hybridizationRules property.
     * 
     * @return
     *     possible object is
     *     {@link S100ICInteroperabilityCatalogue.HybridizationRules }
     *     
     */
    public S100ICInteroperabilityCatalogue.HybridizationRules getHybridizationRules() {
        return hybridizationRules;
    }

    /**
     * Sets the value of the hybridizationRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link S100ICInteroperabilityCatalogue.HybridizationRules }
     *     
     */
    public void setHybridizationRules(S100ICInteroperabilityCatalogue.HybridizationRules value) {
        this.hybridizationRules = value;
    }

    /**
     * Gets the value of the hybridPC property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hybridPC property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHybridPC().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link S100ICInteroperabilityCatalogue.HybridPC }
     * 
     * 
     */
    public List<S100ICInteroperabilityCatalogue.HybridPC> getHybridPC() {
        if (hybridPC == null) {
            hybridPC = new ArrayList<S100ICInteroperabilityCatalogue.HybridPC>();
        }
        return this.hybridPC;
    }

    /**
     * Gets the value of the hybridFC property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hybridFC property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHybridFC().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link S100ICInteroperabilityCatalogue.HybridFC }
     * 
     * 
     */
    public List<S100ICInteroperabilityCatalogue.HybridFC> getHybridFC() {
        if (hybridFC == null) {
            hybridFC = new ArrayList<S100ICInteroperabilityCatalogue.HybridFC>();
        }
        return this.hybridFC;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="S100_IC_DisplayPlane" type="{http://www.iho.int/S100/IC/5.0}S100_IC_DisplayPlane" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "s100ICDisplayPlane"
    })
    public static class DisplayPlanes {

        @XmlElement(name = "S100_IC_DisplayPlane", required = true)
        protected List<S100ICDisplayPlane> s100ICDisplayPlane;

        /**
         * Gets the value of the s100ICDisplayPlane property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the s100ICDisplayPlane property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getS100ICDisplayPlane().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link S100ICDisplayPlane }
         * 
         * 
         */
        public List<S100ICDisplayPlane> getS100ICDisplayPlane() {
            if (s100ICDisplayPlane == null) {
                s100ICDisplayPlane = new ArrayList<S100ICDisplayPlane>();
            }
            return this.s100ICDisplayPlane;
        }

    }


    /**
     * Reference to the hybrid features catalogue
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="S100_IC_HybridFC" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "s100ICHybridFC"
    })
    public static class HybridFC {

        @XmlElement(name = "S100_IC_HybridFC")
        @XmlSchemaType(name = "anyURI")
        protected List<String> s100ICHybridFC;

        /**
         * Gets the value of the s100ICHybridFC property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the s100ICHybridFC property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getS100ICHybridFC().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getS100ICHybridFC() {
            if (s100ICHybridFC == null) {
                s100ICHybridFC = new ArrayList<String>();
            }
            return this.s100ICHybridFC;
        }

    }


    /**
     * Reference to the hybrid portrayals catalogue
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="S100_IC_HybridPC" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "s100ICHybridPC"
    })
    public static class HybridPC {

        @XmlElement(name = "S100_IC_HybridPC")
        @XmlSchemaType(name = "anyURI")
        protected List<String> s100ICHybridPC;

        /**
         * Gets the value of the s100ICHybridPC property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the s100ICHybridPC property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getS100ICHybridPC().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getS100ICHybridPC() {
            if (s100ICHybridPC == null) {
                s100ICHybridPC = new ArrayList<String>();
            }
            return this.s100ICHybridPC;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="S100_IC_SimpleRule" type="{http://www.iho.int/S100/IC/5.0}S100_IC_SimpleRule" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="S100_IC_ThematicRule" type="{http://www.iho.int/S100/IC/5.0}S100_IC_ThematicRule" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="S100_IC_CompleteRule" type="{http://www.iho.int/S100/IC/5.0}S100_IC_CompleteRule" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "s100ICSimpleRule",
        "s100ICThematicRule",
        "s100ICCompleteRule"
    })
    public static class HybridizationRules {

        @XmlElement(name = "S100_IC_SimpleRule")
        protected List<S100ICSimpleRule> s100ICSimpleRule;
        @XmlElement(name = "S100_IC_ThematicRule")
        protected List<S100ICThematicRule> s100ICThematicRule;
        @XmlElement(name = "S100_IC_CompleteRule")
        protected List<S100ICCompleteRule> s100ICCompleteRule;

        /**
         * Gets the value of the s100ICSimpleRule property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the s100ICSimpleRule property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getS100ICSimpleRule().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link S100ICSimpleRule }
         * 
         * 
         */
        public List<S100ICSimpleRule> getS100ICSimpleRule() {
            if (s100ICSimpleRule == null) {
                s100ICSimpleRule = new ArrayList<S100ICSimpleRule>();
            }
            return this.s100ICSimpleRule;
        }

        /**
         * Gets the value of the s100ICThematicRule property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the s100ICThematicRule property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getS100ICThematicRule().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link S100ICThematicRule }
         * 
         * 
         */
        public List<S100ICThematicRule> getS100ICThematicRule() {
            if (s100ICThematicRule == null) {
                s100ICThematicRule = new ArrayList<S100ICThematicRule>();
            }
            return this.s100ICThematicRule;
        }

        /**
         * Gets the value of the s100ICCompleteRule property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the s100ICCompleteRule property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getS100ICCompleteRule().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link S100ICCompleteRule }
         * 
         * 
         */
        public List<S100ICCompleteRule> getS100ICCompleteRule() {
            if (s100ICCompleteRule == null) {
                s100ICCompleteRule = new ArrayList<S100ICCompleteRule>();
            }
            return this.s100ICCompleteRule;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="S100_IC_PredefinedCombination" type="{http://www.iho.int/S100/IC/5.0}S100_IC_PredefinedCombination" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "s100ICPredefinedCombination"
    })
    public static class PredefinedProductCombinations {

        @XmlElement(name = "S100_IC_PredefinedCombination")
        protected List<S100ICPredefinedCombination> s100ICPredefinedCombination;

        /**
         * Gets the value of the s100ICPredefinedCombination property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the s100ICPredefinedCombination property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getS100ICPredefinedCombination().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link S100ICPredefinedCombination }
         * 
         * 
         */
        public List<S100ICPredefinedCombination> getS100ICPredefinedCombination() {
            if (s100ICPredefinedCombination == null) {
                s100ICPredefinedCombination = new ArrayList<S100ICPredefinedCombination>();
            }
            return this.s100ICPredefinedCombination;
        }

    }

}
