//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:26:08 PM PDT 
//


package _int.iho.s100.ic._5;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Information that guides the relative layering and drawing order of feature types during portrayal.
 * 
 * <p>Java class for S100_IC_Feature complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S100_IC_Feature"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="identifier" type="{http://www.iho.int/S100/IC/5.0}GenericIDType"/&gt;
 *         &lt;element name="featureCode" type="{http://www.iho.int/S100/IC/5.0}FeatureCodeType"/&gt;
 *         &lt;element name="product" type="{http://www.iho.int/S100/IC/5.0}dataProduct"/&gt;
 *         &lt;element name="geometryType" type="{http://www.iho.int/S100/IC/5.0}S100_FC_SpatialPrimitiveType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="attributeCombination" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="drawingPriority" type="{http://www.iho.int/S100/IC/5.0}drawingPriorityType"/&gt;
 *         &lt;element name="viewingGroup" type="{http://www.iho.int/S100/IC/5.0}viewingGroupType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S100_IC_Feature", propOrder = {
    "identifier",
    "featureCode",
    "product",
    "geometryType",
    "attributeCombination",
    "drawingPriority",
    "viewingGroup"
})
public class S100ICFeature {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String identifier;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String featureCode;
    @XmlElement(required = true)
    protected DataProduct product;
    @XmlSchemaType(name = "string")
    protected List<S100FCSpatialPrimitiveType> geometryType;
    protected List<String> attributeCombination;
    protected int drawingPriority;
    @XmlElement(required = true)
    protected String viewingGroup;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the featureCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureCode() {
        return featureCode;
    }

    /**
     * Sets the value of the featureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureCode(String value) {
        this.featureCode = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link DataProduct }
     *     
     */
    public DataProduct getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataProduct }
     *     
     */
    public void setProduct(DataProduct value) {
        this.product = value;
    }

    /**
     * Gets the value of the geometryType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geometryType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeometryType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link S100FCSpatialPrimitiveType }
     * 
     * 
     */
    public List<S100FCSpatialPrimitiveType> getGeometryType() {
        if (geometryType == null) {
            geometryType = new ArrayList<S100FCSpatialPrimitiveType>();
        }
        return this.geometryType;
    }

    /**
     * Gets the value of the attributeCombination property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeCombination property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeCombination().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAttributeCombination() {
        if (attributeCombination == null) {
            attributeCombination = new ArrayList<String>();
        }
        return this.attributeCombination;
    }

    /**
     * Gets the value of the drawingPriority property.
     * 
     */
    public int getDrawingPriority() {
        return drawingPriority;
    }

    /**
     * Sets the value of the drawingPriority property.
     * 
     */
    public void setDrawingPriority(int value) {
        this.drawingPriority = value;
    }

    /**
     * Gets the value of the viewingGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewingGroup() {
        return viewingGroup;
    }

    /**
     * Sets the value of the viewingGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewingGroup(String value) {
        this.viewingGroup = value;
    }

}
