//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:23:30 PM PDT 
//


package _int.iho.s100portrayalcatalog._5;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the _int.iho.s100portrayalcatalog._5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PortrayalCatalog_QNAME = new QName("http://www.iho.int/S100PortrayalCatalog/5.2", "portrayalCatalog");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: _int.iho.s100portrayalcatalog._5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PortrayalCatalog }
     * 
     */
    public PortrayalCatalog createPortrayalCatalog() {
        return new PortrayalCatalog();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link ExternalFile }
     * 
     */
    public ExternalFile createExternalFile() {
        return new ExternalFile();
    }

    /**
     * Create an instance of {@link RuleFile }
     * 
     */
    public RuleFile createRuleFile() {
        return new RuleFile();
    }

    /**
     * Create an instance of {@link ViewingGroup }
     * 
     */
    public ViewingGroup createViewingGroup() {
        return new ViewingGroup();
    }

    /**
     * Create an instance of {@link ViewingGroupLayer }
     * 
     */
    public ViewingGroupLayer createViewingGroupLayer() {
        return new ViewingGroupLayer();
    }

    /**
     * Create an instance of {@link DisplayMode }
     * 
     */
    public DisplayMode createDisplayMode() {
        return new DisplayMode();
    }

    /**
     * Create an instance of {@link DisplayPlane }
     * 
     */
    public DisplayPlane createDisplayPlane() {
        return new DisplayPlane();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link EnumerationType }
     * 
     */
    public EnumerationType createEnumerationType() {
        return new EnumerationType();
    }

    /**
     * Create an instance of {@link ConstraintType }
     * 
     */
    public ConstraintType createConstraintType() {
        return new ConstraintType();
    }

    /**
     * Create an instance of {@link ValidationErrorType }
     * 
     */
    public ValidationErrorType createValidationErrorType() {
        return new ValidationErrorType();
    }

    /**
     * Create an instance of {@link ValidationType }
     * 
     */
    public ValidationType createValidationType() {
        return new ValidationType();
    }

    /**
     * Create an instance of {@link ContextParameter }
     * 
     */
    public ContextParameter createContextParameter() {
        return new ContextParameter();
    }

    /**
     * Create an instance of {@link Pixmaps }
     * 
     */
    public Pixmaps createPixmaps() {
        return new Pixmaps();
    }

    /**
     * Create an instance of {@link ColorProfiles }
     * 
     */
    public ColorProfiles createColorProfiles() {
        return new ColorProfiles();
    }

    /**
     * Create an instance of {@link Symbols }
     * 
     */
    public Symbols createSymbols() {
        return new Symbols();
    }

    /**
     * Create an instance of {@link StyleSheets }
     * 
     */
    public StyleSheets createStyleSheets() {
        return new StyleSheets();
    }

    /**
     * Create an instance of {@link LineStyles }
     * 
     */
    public LineStyles createLineStyles() {
        return new LineStyles();
    }

    /**
     * Create an instance of {@link AreaFills }
     * 
     */
    public AreaFills createAreaFills() {
        return new AreaFills();
    }

    /**
     * Create an instance of {@link Fonts }
     * 
     */
    public Fonts createFonts() {
        return new Fonts();
    }

    /**
     * Create an instance of {@link ViewingGroups }
     * 
     */
    public ViewingGroups createViewingGroups() {
        return new ViewingGroups();
    }

    /**
     * Create an instance of {@link ViewingGroupLayers }
     * 
     */
    public ViewingGroupLayers createViewingGroupLayers() {
        return new ViewingGroupLayers();
    }

    /**
     * Create an instance of {@link DisplayModes }
     * 
     */
    public DisplayModes createDisplayModes() {
        return new DisplayModes();
    }

    /**
     * Create an instance of {@link DisplayPlanes }
     * 
     */
    public DisplayPlanes createDisplayPlanes() {
        return new DisplayPlanes();
    }

    /**
     * Create an instance of {@link Context }
     * 
     */
    public Context createContext() {
        return new Context();
    }

    /**
     * Create an instance of {@link Rules }
     * 
     */
    public Rules createRules() {
        return new Rules();
    }

    /**
     * Create an instance of {@link PortrayalCatalog.FoundationMode }
     * 
     */
    public PortrayalCatalog.FoundationMode createPortrayalCatalogFoundationMode() {
        return new PortrayalCatalog.FoundationMode();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PortrayalCatalog }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PortrayalCatalog }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.iho.int/S100PortrayalCatalog/5.2", name = "portrayalCatalog")
    public JAXBElement<PortrayalCatalog> createPortrayalCatalog(PortrayalCatalog value) {
        return new JAXBElement<PortrayalCatalog>(_PortrayalCatalog_QNAME, PortrayalCatalog.class, null, value);
    }

}
