//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:23:30 PM PDT 
//


package _int.iho.s100portrayalcatalog._5;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A container of all the Catalogue items
 * 
 * <p>Java class for PortrayalCatalog complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PortrayalCatalog"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="alertCatalog" type="{http://www.iho.int/S100PortrayalCatalog/5.2}ExternalFile" minOccurs="0"/&gt;
 *         &lt;element name="pixmaps" type="{http://www.iho.int/S100PortrayalCatalog/5.2}Pixmaps"/&gt;
 *         &lt;element name="colorProfiles" type="{http://www.iho.int/S100PortrayalCatalog/5.2}ColorProfiles"/&gt;
 *         &lt;element name="symbols" type="{http://www.iho.int/S100PortrayalCatalog/5.2}Symbols"/&gt;
 *         &lt;element name="styleSheets" type="{http://www.iho.int/S100PortrayalCatalog/5.2}StyleSheets"/&gt;
 *         &lt;element name="lineStyles" type="{http://www.iho.int/S100PortrayalCatalog/5.2}LineStyles"/&gt;
 *         &lt;element name="areaFills" type="{http://www.iho.int/S100PortrayalCatalog/5.2}AreaFills"/&gt;
 *         &lt;element name="fonts" type="{http://www.iho.int/S100PortrayalCatalog/5.2}Fonts"/&gt;
 *         &lt;element name="viewingGroups" type="{http://www.iho.int/S100PortrayalCatalog/5.2}ViewingGroups"/&gt;
 *         &lt;element name="foundationMode"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="viewingGroup" type="{http://www.iho.int/S100SymbolDefinition/5.2}IdString" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="viewingGroupLayers" type="{http://www.iho.int/S100PortrayalCatalog/5.2}ViewingGroupLayers"/&gt;
 *         &lt;element name="displayModes" type="{http://www.iho.int/S100PortrayalCatalog/5.2}DisplayModes"/&gt;
 *         &lt;element name="displayPlanes" type="{http://www.iho.int/S100PortrayalCatalog/5.2}DisplayPlanes"/&gt;
 *         &lt;element name="context" type="{http://www.iho.int/S100PortrayalCatalog/5.2}Context"/&gt;
 *         &lt;element name="rules" type="{http://www.iho.int/S100PortrayalCatalog/5.2}Rules"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="productId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PortrayalCatalog", propOrder = {
    "alertCatalog",
    "pixmaps",
    "colorProfiles",
    "symbols",
    "styleSheets",
    "lineStyles",
    "areaFills",
    "fonts",
    "viewingGroups",
    "foundationMode",
    "viewingGroupLayers",
    "displayModes",
    "displayPlanes",
    "context",
    "rules"
})
public class PortrayalCatalog {

    protected ExternalFile alertCatalog;
    @XmlElement(required = true)
    protected Pixmaps pixmaps;
    @XmlElement(required = true)
    protected ColorProfiles colorProfiles;
    @XmlElement(required = true)
    protected Symbols symbols;
    @XmlElement(required = true)
    protected StyleSheets styleSheets;
    @XmlElement(required = true)
    protected LineStyles lineStyles;
    @XmlElement(required = true)
    protected AreaFills areaFills;
    @XmlElement(required = true)
    protected Fonts fonts;
    @XmlElement(required = true)
    protected ViewingGroups viewingGroups;
    @XmlElement(required = true)
    protected PortrayalCatalog.FoundationMode foundationMode;
    @XmlElement(required = true)
    protected ViewingGroupLayers viewingGroupLayers;
    @XmlElement(required = true)
    protected DisplayModes displayModes;
    @XmlElement(required = true)
    protected DisplayPlanes displayPlanes;
    @XmlElement(required = true)
    protected Context context;
    @XmlElement(required = true)
    protected Rules rules;
    @XmlAttribute(name = "productId", required = true)
    protected String productId;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the alertCatalog property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalFile }
     *     
     */
    public ExternalFile getAlertCatalog() {
        return alertCatalog;
    }

    /**
     * Sets the value of the alertCatalog property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalFile }
     *     
     */
    public void setAlertCatalog(ExternalFile value) {
        this.alertCatalog = value;
    }

    /**
     * Gets the value of the pixmaps property.
     * 
     * @return
     *     possible object is
     *     {@link Pixmaps }
     *     
     */
    public Pixmaps getPixmaps() {
        return pixmaps;
    }

    /**
     * Sets the value of the pixmaps property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pixmaps }
     *     
     */
    public void setPixmaps(Pixmaps value) {
        this.pixmaps = value;
    }

    /**
     * Gets the value of the colorProfiles property.
     * 
     * @return
     *     possible object is
     *     {@link ColorProfiles }
     *     
     */
    public ColorProfiles getColorProfiles() {
        return colorProfiles;
    }

    /**
     * Sets the value of the colorProfiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorProfiles }
     *     
     */
    public void setColorProfiles(ColorProfiles value) {
        this.colorProfiles = value;
    }

    /**
     * Gets the value of the symbols property.
     * 
     * @return
     *     possible object is
     *     {@link Symbols }
     *     
     */
    public Symbols getSymbols() {
        return symbols;
    }

    /**
     * Sets the value of the symbols property.
     * 
     * @param value
     *     allowed object is
     *     {@link Symbols }
     *     
     */
    public void setSymbols(Symbols value) {
        this.symbols = value;
    }

    /**
     * Gets the value of the styleSheets property.
     * 
     * @return
     *     possible object is
     *     {@link StyleSheets }
     *     
     */
    public StyleSheets getStyleSheets() {
        return styleSheets;
    }

    /**
     * Sets the value of the styleSheets property.
     * 
     * @param value
     *     allowed object is
     *     {@link StyleSheets }
     *     
     */
    public void setStyleSheets(StyleSheets value) {
        this.styleSheets = value;
    }

    /**
     * Gets the value of the lineStyles property.
     * 
     * @return
     *     possible object is
     *     {@link LineStyles }
     *     
     */
    public LineStyles getLineStyles() {
        return lineStyles;
    }

    /**
     * Sets the value of the lineStyles property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineStyles }
     *     
     */
    public void setLineStyles(LineStyles value) {
        this.lineStyles = value;
    }

    /**
     * Gets the value of the areaFills property.
     * 
     * @return
     *     possible object is
     *     {@link AreaFills }
     *     
     */
    public AreaFills getAreaFills() {
        return areaFills;
    }

    /**
     * Sets the value of the areaFills property.
     * 
     * @param value
     *     allowed object is
     *     {@link AreaFills }
     *     
     */
    public void setAreaFills(AreaFills value) {
        this.areaFills = value;
    }

    /**
     * Gets the value of the fonts property.
     * 
     * @return
     *     possible object is
     *     {@link Fonts }
     *     
     */
    public Fonts getFonts() {
        return fonts;
    }

    /**
     * Sets the value of the fonts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fonts }
     *     
     */
    public void setFonts(Fonts value) {
        this.fonts = value;
    }

    /**
     * Gets the value of the viewingGroups property.
     * 
     * @return
     *     possible object is
     *     {@link ViewingGroups }
     *     
     */
    public ViewingGroups getViewingGroups() {
        return viewingGroups;
    }

    /**
     * Sets the value of the viewingGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewingGroups }
     *     
     */
    public void setViewingGroups(ViewingGroups value) {
        this.viewingGroups = value;
    }

    /**
     * Gets the value of the foundationMode property.
     * 
     * @return
     *     possible object is
     *     {@link PortrayalCatalog.FoundationMode }
     *     
     */
    public PortrayalCatalog.FoundationMode getFoundationMode() {
        return foundationMode;
    }

    /**
     * Sets the value of the foundationMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortrayalCatalog.FoundationMode }
     *     
     */
    public void setFoundationMode(PortrayalCatalog.FoundationMode value) {
        this.foundationMode = value;
    }

    /**
     * Gets the value of the viewingGroupLayers property.
     * 
     * @return
     *     possible object is
     *     {@link ViewingGroupLayers }
     *     
     */
    public ViewingGroupLayers getViewingGroupLayers() {
        return viewingGroupLayers;
    }

    /**
     * Sets the value of the viewingGroupLayers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewingGroupLayers }
     *     
     */
    public void setViewingGroupLayers(ViewingGroupLayers value) {
        this.viewingGroupLayers = value;
    }

    /**
     * Gets the value of the displayModes property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayModes }
     *     
     */
    public DisplayModes getDisplayModes() {
        return displayModes;
    }

    /**
     * Sets the value of the displayModes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayModes }
     *     
     */
    public void setDisplayModes(DisplayModes value) {
        this.displayModes = value;
    }

    /**
     * Gets the value of the displayPlanes property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayPlanes }
     *     
     */
    public DisplayPlanes getDisplayPlanes() {
        return displayPlanes;
    }

    /**
     * Sets the value of the displayPlanes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayPlanes }
     *     
     */
    public void setDisplayPlanes(DisplayPlanes value) {
        this.displayPlanes = value;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link Context }
     *     
     */
    public Context getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link Context }
     *     
     */
    public void setContext(Context value) {
        this.context = value;
    }

    /**
     * Gets the value of the rules property.
     * 
     * @return
     *     possible object is
     *     {@link Rules }
     *     
     */
    public Rules getRules() {
        return rules;
    }

    /**
     * Sets the value of the rules property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rules }
     *     
     */
    public void setRules(Rules value) {
        this.rules = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="viewingGroup" type="{http://www.iho.int/S100SymbolDefinition/5.2}IdString" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "viewingGroup"
    })
    public static class FoundationMode {

        protected List<String> viewingGroup;

        /**
         * Gets the value of the viewingGroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the viewingGroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getViewingGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getViewingGroup() {
            if (viewingGroup == null) {
                viewingGroup = new ArrayList<String>();
            }
            return this.viewingGroup;
        }

    }

}
