//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:23:30 PM PDT 
//


package _int.iho.s100portrayalcatalog._5;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RuleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="RuleType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="TopLevelTemplate"/&gt;
 *     &lt;enumeration value="SubTemplate"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RuleType")
@XmlEnum
public enum RuleType {


    /**
     * The rule file contains a top level template
     * 
     */
    @XmlEnumValue("TopLevelTemplate")
    TOP_LEVEL_TEMPLATE("TopLevelTemplate"),

    /**
     * The rule file contains templates that are used or called by other templates
     * 
     */
    @XmlEnumValue("SubTemplate")
    SUB_TEMPLATE("SubTemplate");
    private final String value;

    RuleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RuleType fromValue(String v) {
        for (RuleType c: RuleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
