//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:32:41 PM PDT 
//


package org.iso.standards.iso._19115.__3.cit._2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import org.iso.standards.iso._19115.__3.gco._1.CodeListValueType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.iso.standards.iso._19115.__3.cit._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CIAddress_QNAME = new QName("http://standards.iso.org/iso/19115/-3/cit/2.0", "CI_Address");
    private final static QName _CICitation_QNAME = new QName("http://standards.iso.org/iso/19115/-3/cit/2.0", "CI_Citation");
    private final static QName _CIContact_QNAME = new QName("http://standards.iso.org/iso/19115/-3/cit/2.0", "CI_Contact");
    private final static QName _CIDate_QNAME = new QName("http://standards.iso.org/iso/19115/-3/cit/2.0", "CI_Date");
    private final static QName _CIDateTypeCode_QNAME = new QName("http://standards.iso.org/iso/19115/-3/cit/2.0", "CI_DateTypeCode");
    private final static QName _CIIndividual_QNAME = new QName("http://standards.iso.org/iso/19115/-3/cit/2.0", "CI_Individual");
    private final static QName _AbstractCIParty_QNAME = new QName("http://standards.iso.org/iso/19115/-3/cit/2.0", "AbstractCI_Party");
    private final static QName _CIOnLineFunctionCode_QNAME = new QName("http://standards.iso.org/iso/19115/-3/cit/2.0", "CI_OnLineFunctionCode");
    private final static QName _CIOnlineResource_QNAME = new QName("http://standards.iso.org/iso/19115/-3/cit/2.0", "CI_OnlineResource");
    private final static QName _CIOrganisation_QNAME = new QName("http://standards.iso.org/iso/19115/-3/cit/2.0", "CI_Organisation");
    private final static QName _CIPresentationFormCode_QNAME = new QName("http://standards.iso.org/iso/19115/-3/cit/2.0", "CI_PresentationFormCode");
    private final static QName _CIResponsibility_QNAME = new QName("http://standards.iso.org/iso/19115/-3/cit/2.0", "CI_Responsibility");
    private final static QName _CIRoleCode_QNAME = new QName("http://standards.iso.org/iso/19115/-3/cit/2.0", "CI_RoleCode");
    private final static QName _CISeries_QNAME = new QName("http://standards.iso.org/iso/19115/-3/cit/2.0", "CI_Series");
    private final static QName _CITelephone_QNAME = new QName("http://standards.iso.org/iso/19115/-3/cit/2.0", "CI_Telephone");
    private final static QName _CITelephoneTypeCode_QNAME = new QName("http://standards.iso.org/iso/19115/-3/cit/2.0", "CI_TelephoneTypeCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.iso.standards.iso._19115.__3.cit._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CIAddressType }
     * 
     */
    public CIAddressType createCIAddressType() {
        return new CIAddressType();
    }

    /**
     * Create an instance of {@link CICitationType }
     * 
     */
    public CICitationType createCICitationType() {
        return new CICitationType();
    }

    /**
     * Create an instance of {@link CIContactType }
     * 
     */
    public CIContactType createCIContactType() {
        return new CIContactType();
    }

    /**
     * Create an instance of {@link CIDateType }
     * 
     */
    public CIDateType createCIDateType() {
        return new CIDateType();
    }

    /**
     * Create an instance of {@link CIIndividualType }
     * 
     */
    public CIIndividualType createCIIndividualType() {
        return new CIIndividualType();
    }

    /**
     * Create an instance of {@link CIOnlineResourceType }
     * 
     */
    public CIOnlineResourceType createCIOnlineResourceType() {
        return new CIOnlineResourceType();
    }

    /**
     * Create an instance of {@link CIOrganisationType }
     * 
     */
    public CIOrganisationType createCIOrganisationType() {
        return new CIOrganisationType();
    }

    /**
     * Create an instance of {@link CIResponsibilityType }
     * 
     */
    public CIResponsibilityType createCIResponsibilityType() {
        return new CIResponsibilityType();
    }

    /**
     * Create an instance of {@link CISeriesType }
     * 
     */
    public CISeriesType createCISeriesType() {
        return new CISeriesType();
    }

    /**
     * Create an instance of {@link CITelephoneType }
     * 
     */
    public CITelephoneType createCITelephoneType() {
        return new CITelephoneType();
    }

    /**
     * Create an instance of {@link CIAddressPropertyType }
     * 
     */
    public CIAddressPropertyType createCIAddressPropertyType() {
        return new CIAddressPropertyType();
    }

    /**
     * Create an instance of {@link CICitationPropertyType }
     * 
     */
    public CICitationPropertyType createCICitationPropertyType() {
        return new CICitationPropertyType();
    }

    /**
     * Create an instance of {@link CIContactPropertyType }
     * 
     */
    public CIContactPropertyType createCIContactPropertyType() {
        return new CIContactPropertyType();
    }

    /**
     * Create an instance of {@link CIDatePropertyType }
     * 
     */
    public CIDatePropertyType createCIDatePropertyType() {
        return new CIDatePropertyType();
    }

    /**
     * Create an instance of {@link CIDateTypeCodePropertyType }
     * 
     */
    public CIDateTypeCodePropertyType createCIDateTypeCodePropertyType() {
        return new CIDateTypeCodePropertyType();
    }

    /**
     * Create an instance of {@link CIIndividualPropertyType }
     * 
     */
    public CIIndividualPropertyType createCIIndividualPropertyType() {
        return new CIIndividualPropertyType();
    }

    /**
     * Create an instance of {@link CIOnLineFunctionCodePropertyType }
     * 
     */
    public CIOnLineFunctionCodePropertyType createCIOnLineFunctionCodePropertyType() {
        return new CIOnLineFunctionCodePropertyType();
    }

    /**
     * Create an instance of {@link CIOnlineResourcePropertyType }
     * 
     */
    public CIOnlineResourcePropertyType createCIOnlineResourcePropertyType() {
        return new CIOnlineResourcePropertyType();
    }

    /**
     * Create an instance of {@link CIOrganisationPropertyType }
     * 
     */
    public CIOrganisationPropertyType createCIOrganisationPropertyType() {
        return new CIOrganisationPropertyType();
    }

    /**
     * Create an instance of {@link AbstractCIPartyPropertyType }
     * 
     */
    public AbstractCIPartyPropertyType createAbstractCIPartyPropertyType() {
        return new AbstractCIPartyPropertyType();
    }

    /**
     * Create an instance of {@link CIPresentationFormCodePropertyType }
     * 
     */
    public CIPresentationFormCodePropertyType createCIPresentationFormCodePropertyType() {
        return new CIPresentationFormCodePropertyType();
    }

    /**
     * Create an instance of {@link CIResponsibilityPropertyType }
     * 
     */
    public CIResponsibilityPropertyType createCIResponsibilityPropertyType() {
        return new CIResponsibilityPropertyType();
    }

    /**
     * Create an instance of {@link CIRoleCodePropertyType }
     * 
     */
    public CIRoleCodePropertyType createCIRoleCodePropertyType() {
        return new CIRoleCodePropertyType();
    }

    /**
     * Create an instance of {@link CISeriesPropertyType }
     * 
     */
    public CISeriesPropertyType createCISeriesPropertyType() {
        return new CISeriesPropertyType();
    }

    /**
     * Create an instance of {@link CITelephonePropertyType }
     * 
     */
    public CITelephonePropertyType createCITelephonePropertyType() {
        return new CITelephonePropertyType();
    }

    /**
     * Create an instance of {@link CITelephoneTypeCodePropertyType }
     * 
     */
    public CITelephoneTypeCodePropertyType createCITelephoneTypeCodePropertyType() {
        return new CITelephoneTypeCodePropertyType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIAddressType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CIAddressType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/cit/2.0", name = "CI_Address", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<CIAddressType> createCIAddress(CIAddressType value) {
        return new JAXBElement<CIAddressType>(_CIAddress_QNAME, CIAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CICitationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CICitationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/cit/2.0", name = "CI_Citation", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", substitutionHeadName = "Abstract_Citation")
    public JAXBElement<CICitationType> createCICitation(CICitationType value) {
        return new JAXBElement<CICitationType>(_CICitation_QNAME, CICitationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIContactType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CIContactType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/cit/2.0", name = "CI_Contact", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<CIContactType> createCIContact(CIContactType value) {
        return new JAXBElement<CIContactType>(_CIContact_QNAME, CIContactType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIDateType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CIDateType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/cit/2.0", name = "CI_Date", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", substitutionHeadName = "Abstract_TypedDate")
    public JAXBElement<CIDateType> createCIDate(CIDateType value) {
        return new JAXBElement<CIDateType>(_CIDate_QNAME, CIDateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeListValueType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CodeListValueType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/cit/2.0", name = "CI_DateTypeCode", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "CharacterString")
    public JAXBElement<CodeListValueType> createCIDateTypeCode(CodeListValueType value) {
        return new JAXBElement<CodeListValueType>(_CIDateTypeCode_QNAME, CodeListValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIIndividualType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CIIndividualType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/cit/2.0", name = "CI_Individual", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/cit/2.0", substitutionHeadName = "AbstractCI_Party")
    public JAXBElement<CIIndividualType> createCIIndividual(CIIndividualType value) {
        return new JAXBElement<CIIndividualType>(_CIIndividual_QNAME, CIIndividualType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractCIPartyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractCIPartyType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/cit/2.0", name = "AbstractCI_Party", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractCIPartyType> createAbstractCIParty(AbstractCIPartyType value) {
        return new JAXBElement<AbstractCIPartyType>(_AbstractCIParty_QNAME, AbstractCIPartyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeListValueType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CodeListValueType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/cit/2.0", name = "CI_OnLineFunctionCode", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "CharacterString")
    public JAXBElement<CodeListValueType> createCIOnLineFunctionCode(CodeListValueType value) {
        return new JAXBElement<CodeListValueType>(_CIOnLineFunctionCode_QNAME, CodeListValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIOnlineResourceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CIOnlineResourceType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/cit/2.0", name = "CI_OnlineResource", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", substitutionHeadName = "Abstract_OnlineResource")
    public JAXBElement<CIOnlineResourceType> createCIOnlineResource(CIOnlineResourceType value) {
        return new JAXBElement<CIOnlineResourceType>(_CIOnlineResource_QNAME, CIOnlineResourceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIOrganisationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CIOrganisationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/cit/2.0", name = "CI_Organisation", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/cit/2.0", substitutionHeadName = "AbstractCI_Party")
    public JAXBElement<CIOrganisationType> createCIOrganisation(CIOrganisationType value) {
        return new JAXBElement<CIOrganisationType>(_CIOrganisation_QNAME, CIOrganisationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeListValueType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CodeListValueType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/cit/2.0", name = "CI_PresentationFormCode", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "CharacterString")
    public JAXBElement<CodeListValueType> createCIPresentationFormCode(CodeListValueType value) {
        return new JAXBElement<CodeListValueType>(_CIPresentationFormCode_QNAME, CodeListValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIResponsibilityType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CIResponsibilityType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/cit/2.0", name = "CI_Responsibility", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", substitutionHeadName = "Abstract_Responsibility")
    public JAXBElement<CIResponsibilityType> createCIResponsibility(CIResponsibilityType value) {
        return new JAXBElement<CIResponsibilityType>(_CIResponsibility_QNAME, CIResponsibilityType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeListValueType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CodeListValueType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/cit/2.0", name = "CI_RoleCode", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "CharacterString")
    public JAXBElement<CodeListValueType> createCIRoleCode(CodeListValueType value) {
        return new JAXBElement<CodeListValueType>(_CIRoleCode_QNAME, CodeListValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CISeriesType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CISeriesType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/cit/2.0", name = "CI_Series", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<CISeriesType> createCISeries(CISeriesType value) {
        return new JAXBElement<CISeriesType>(_CISeries_QNAME, CISeriesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CITelephoneType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CITelephoneType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/cit/2.0", name = "CI_Telephone", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<CITelephoneType> createCITelephone(CITelephoneType value) {
        return new JAXBElement<CITelephoneType>(_CITelephone_QNAME, CITelephoneType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeListValueType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CodeListValueType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/cit/2.0", name = "CI_TelephoneTypeCode", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "CharacterString")
    public JAXBElement<CodeListValueType> createCITelephoneTypeCode(CodeListValueType value) {
        return new JAXBElement<CodeListValueType>(_CITelephoneTypeCode_QNAME, CodeListValueType.class, null, value);
    }

}
