//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:23:30 PM PDT 
//


package _int.iho.s100symboldefinition._5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines the placement of a symbol within an area
 * 
 * <p>Java class for AreaSymbolPlacement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AreaSymbolPlacement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="placementMode" type="{http://www.iho.int/S100SymbolDefinition/5.2}AreaPlacementMode" default="VisibleParts" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AreaSymbolPlacement")
public class AreaSymbolPlacement {

    @XmlAttribute(name = "placementMode")
    protected AreaPlacementMode placementMode;

    /**
     * Gets the value of the placementMode property.
     * 
     * @return
     *     possible object is
     *     {@link AreaPlacementMode }
     *     
     */
    public AreaPlacementMode getPlacementMode() {
        if (placementMode == null) {
            return AreaPlacementMode.VISIBLE_PARTS;
        } else {
            return placementMode;
        }
    }

    /**
     * Sets the value of the placementMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AreaPlacementMode }
     *     
     */
    public void setPlacementMode(AreaPlacementMode value) {
        this.placementMode = value;
    }

}
