//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:23:30 PM PDT 
//


package _int.iho.s100symboldefinition._5;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * A line style made with an aggregation of other line styles
 * 
 * <p>Java class for CompositeLineStyle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompositeLineStyle"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.iho.int/S100SymbolDefinition/5.2}LineStyleBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{http://www.iho.int/S100SymbolDefinition/5.2}LineStyleGroup" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompositeLineStyle", propOrder = {
    "lineStyleGroup"
})
public class CompositeLineStyle
    extends LineStyleBase
{

    @XmlElements({
        @XmlElement(name = "lineStyle", type = LineStyle.class),
        @XmlElement(name = "lineStyleReference", type = LineStyleReference.class),
        @XmlElement(name = "compositeLineStyle", type = CompositeLineStyle.class)
    })
    protected List<LineStyleBase> lineStyleGroup;

    /**
     * The components of the composite line style Gets the value of the lineStyleGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineStyleGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineStyleGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompositeLineStyle }
     * {@link LineStyle }
     * {@link LineStyleReference }
     * 
     * 
     */
    public List<LineStyleBase> getLineStyleGroup() {
        if (lineStyleGroup == null) {
            lineStyleGroup = new ArrayList<LineStyleBase>();
        }
        return this.lineStyleGroup;
    }

}
