//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:23:30 PM PDT 
//


package _int.iho.s100symboldefinition._5;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FontProportion.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="FontProportion"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="MonoSpaced"/&gt;
 *     &lt;enumeration value="Proportional"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FontProportion")
@XmlEnum
public enum FontProportion {


    /**
     * All typefaces in a font have the same width, also known as ‘typewriter’ fonts
     * 
     */
    @XmlEnumValue("MonoSpaced")
    MONO_SPACED("MonoSpaced"),

    /**
     * Any typeface in the font as its individual width
     * 
     */
    @XmlEnumValue("Proportional")
    PROPORTIONAL("Proportional");
    private final String value;

    FontProportion(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FontProportion fromValue(String v) {
        for (FontProportion c: FontProportion.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
