//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:23:30 PM PDT 
//


package _int.iho.s100symboldefinition._5;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HorizontalAlignment.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="HorizontalAlignment"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Start"/&gt;
 *     &lt;enumeration value="End"/&gt;
 *     &lt;enumeration value="Center"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "HorizontalAlignment")
@XmlEnum
public enum HorizontalAlignment {


    /**
     * The anchor point is at the start of the text
     * 
     */
    @XmlEnumValue("Start")
    START("Start"),

    /**
     * The anchor point is at the end of the text
     * 
     */
    @XmlEnumValue("End")
    END("End"),

    /**
     * The anchor point is at the (horizontal) centre of the text
     * 
     */
    @XmlEnumValue("Center")
    CENTER("Center");
    private final String value;

    HorizontalAlignment(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HorizontalAlignment fromValue(String v) {
        for (HorizontalAlignment c: HorizontalAlignment.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
