//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:23:30 PM PDT 
//


package _int.iho.s100symboldefinition._5;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JoinStyle.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="JoinStyle"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Bevel"/&gt;
 *     &lt;enumeration value="Miter"/&gt;
 *     &lt;enumeration value="Round"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "JoinStyle")
@XmlEnum
public enum JoinStyle {


    /**
     * Bevel
     * 
     */
    @XmlEnumValue("Bevel")
    BEVEL("Bevel"),

    /**
     * Miter
     * 
     */
    @XmlEnumValue("Miter")
    MITER("Miter"),

    /**
     * Round
     * 
     */
    @XmlEnumValue("Round")
    ROUND("Round");
    private final String value;

    JoinStyle(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static JoinStyle fromValue(String v) {
        for (JoinStyle c: JoinStyle.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
