//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:23:30 PM PDT 
//


package _int.iho.s100symboldefinition._5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines the placement of a symbol along a line
 * 
 * <p>Java class for LineSymbolPlacement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LineSymbolPlacement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="offset" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="placementMode" use="required" type="{http://www.iho.int/S100SymbolDefinition/5.2}LinePlacementMode" /&gt;
 *       &lt;attribute name="visibleParts" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LineSymbolPlacement", propOrder = {
    "offset"
})
public class LineSymbolPlacement {

    protected double offset;
    @XmlAttribute(name = "placementMode", required = true)
    protected LinePlacementMode placementMode;
    @XmlAttribute(name = "visibleParts")
    protected Boolean visibleParts;

    /**
     * Gets the value of the offset property.
     * 
     */
    public double getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     */
    public void setOffset(double value) {
        this.offset = value;
    }

    /**
     * Gets the value of the placementMode property.
     * 
     * @return
     *     possible object is
     *     {@link LinePlacementMode }
     *     
     */
    public LinePlacementMode getPlacementMode() {
        return placementMode;
    }

    /**
     * Sets the value of the placementMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinePlacementMode }
     *     
     */
    public void setPlacementMode(LinePlacementMode value) {
        this.placementMode = value;
    }

    /**
     * Gets the value of the visibleParts property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isVisibleParts() {
        if (visibleParts == null) {
            return false;
        } else {
            return visibleParts;
        }
    }

    /**
     * Sets the value of the visibleParts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisibleParts(Boolean value) {
        this.visibleParts = value;
    }

}
