//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:23:30 PM PDT 
//


package _int.iho.s100symboldefinition._5;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * A two dimensional graphical element
 * 
 * <p>Java class for Symbol complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Symbol"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="offset" type="{http://www.iho.int/S100SymbolDefinition/5.2}Vector" minOccurs="0"/&gt;
 *         &lt;element name="overrideAll" type="{http://www.iho.int/S100SymbolDefinition/5.2}Color" minOccurs="0"/&gt;
 *         &lt;element name="override" type="{http://www.iho.int/S100SymbolDefinition/5.2}OverrideColor" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="linePlacement" type="{http://www.iho.int/S100SymbolDefinition/5.2}LineSymbolPlacement" minOccurs="0"/&gt;
 *         &lt;element name="areaPlacement" type="{http://www.iho.int/S100SymbolDefinition/5.2}AreaSymbolPlacement" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="reference" use="required" type="{http://www.iho.int/S100SymbolDefinition/5.2}IdString" /&gt;
 *       &lt;attribute name="rotation" type="{http://www.w3.org/2001/XMLSchema}double" default="0.0" /&gt;
 *       &lt;attribute name="rotationCRS" type="{http://www.iho.int/S100SymbolDefinition/5.2}CRSType" default="PortrayalCRS" /&gt;
 *       &lt;attribute name="scaleFactor" type="{http://www.w3.org/2001/XMLSchema}double" default="1.0" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Symbol", propOrder = {
    "offset",
    "overrideAll",
    "override",
    "linePlacement",
    "areaPlacement"
})
public class Symbol {

    protected Vector offset;
    protected Color overrideAll;
    protected List<OverrideColor> override;
    protected LineSymbolPlacement linePlacement;
    protected AreaSymbolPlacement areaPlacement;
    @XmlAttribute(name = "reference", required = true)
    protected String reference;
    @XmlAttribute(name = "rotation")
    protected Double rotation;
    @XmlAttribute(name = "rotationCRS")
    protected CRSType rotationCRS;
    @XmlAttribute(name = "scaleFactor")
    protected Double scaleFactor;

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link Vector }
     *     
     */
    public Vector getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector }
     *     
     */
    public void setOffset(Vector value) {
        this.offset = value;
    }

    /**
     * Gets the value of the overrideAll property.
     * 
     * @return
     *     possible object is
     *     {@link Color }
     *     
     */
    public Color getOverrideAll() {
        return overrideAll;
    }

    /**
     * Sets the value of the overrideAll property.
     * 
     * @param value
     *     allowed object is
     *     {@link Color }
     *     
     */
    public void setOverrideAll(Color value) {
        this.overrideAll = value;
    }

    /**
     * Gets the value of the override property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the override property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOverride().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OverrideColor }
     * 
     * 
     */
    public List<OverrideColor> getOverride() {
        if (override == null) {
            override = new ArrayList<OverrideColor>();
        }
        return this.override;
    }

    /**
     * Gets the value of the linePlacement property.
     * 
     * @return
     *     possible object is
     *     {@link LineSymbolPlacement }
     *     
     */
    public LineSymbolPlacement getLinePlacement() {
        return linePlacement;
    }

    /**
     * Sets the value of the linePlacement property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineSymbolPlacement }
     *     
     */
    public void setLinePlacement(LineSymbolPlacement value) {
        this.linePlacement = value;
    }

    /**
     * Gets the value of the areaPlacement property.
     * 
     * @return
     *     possible object is
     *     {@link AreaSymbolPlacement }
     *     
     */
    public AreaSymbolPlacement getAreaPlacement() {
        return areaPlacement;
    }

    /**
     * Sets the value of the areaPlacement property.
     * 
     * @param value
     *     allowed object is
     *     {@link AreaSymbolPlacement }
     *     
     */
    public void setAreaPlacement(AreaSymbolPlacement value) {
        this.areaPlacement = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        this.reference = value;
    }

    /**
     * Gets the value of the rotation property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getRotation() {
        if (rotation == null) {
            return  0.0D;
        } else {
            return rotation;
        }
    }

    /**
     * Sets the value of the rotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRotation(Double value) {
        this.rotation = value;
    }

    /**
     * Gets the value of the rotationCRS property.
     * 
     * @return
     *     possible object is
     *     {@link CRSType }
     *     
     */
    public CRSType getRotationCRS() {
        if (rotationCRS == null) {
            return CRSType.PORTRAYAL_CRS;
        } else {
            return rotationCRS;
        }
    }

    /**
     * Sets the value of the rotationCRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link CRSType }
     *     
     */
    public void setRotationCRS(CRSType value) {
        this.rotationCRS = value;
    }

    /**
     * Gets the value of the scaleFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getScaleFactor() {
        if (scaleFactor == null) {
            return  1.0D;
        } else {
            return scaleFactor;
        }
    }

    /**
     * Sets the value of the scaleFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setScaleFactor(Double value) {
        this.scaleFactor = value;
    }

}
