//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:23:30 PM PDT 
//


package _int.iho.s100presentation._5;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * A ordered set of Drawing Instructions
 * 
 * <p>Java class for DisplayList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DisplayList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{http://www.iho.int/S100Presentation/5.2}DisplayInstruction" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DisplayList", propOrder = {
    "displayInstruction"
})
public class DisplayList {

    @XmlElements({
        @XmlElement(name = "nullInstruction", type = NullInstruction.class),
        @XmlElement(name = "pointInstruction", type = PointInstruction.class),
        @XmlElement(name = "lineInstruction", type = LineInstruction.class),
        @XmlElement(name = "areaInstruction", type = AreaInstruction.class),
        @XmlElement(name = "coverageInstruction", type = CoverageInstruction.class),
        @XmlElement(name = "textInstruction", type = TextInstruction.class),
        @XmlElement(name = "augmentedPoint", type = AugmentedPoint.class),
        @XmlElement(name = "augmentedRay", type = AugmentedRay.class),
        @XmlElement(name = "augmentedPath", type = AugmentedPath.class),
        @XmlElement(name = "augmentedArea", type = AugmentedArea.class)
    })
    protected List<DrawingInstruction> displayInstruction;

    /**
     * An instruction of this list Gets the value of the displayInstruction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the displayInstruction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisplayInstruction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AreaInstruction }
     * {@link AugmentedArea }
     * {@link AugmentedPath }
     * {@link AugmentedPoint }
     * {@link AugmentedRay }
     * {@link CoverageInstruction }
     * {@link LineInstruction }
     * {@link NullInstruction }
     * {@link PointInstruction }
     * {@link TextInstruction }
     * 
     * 
     */
    public List<DrawingInstruction> getDisplayInstruction() {
        if (displayInstruction == null) {
            displayInstruction = new ArrayList<DrawingInstruction>();
        }
        return this.displayInstruction;
    }

}
