//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:27:16 PM PDT 
//


package _int.iho.s100.xc._5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.iso.standards.iso._19115.__3.mco._1.MDClassificationCodePropertyType;


/**
 * Classification code derivation from ISO 19115
 * 
 * <p>Java class for S100_ClassificationCode_PropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S100_ClassificationCode_PropertyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://standards.iso.org/iso/19115/-3/mco/1.0}MD_ClassificationCode_PropertyType"&gt;
 *       &lt;attribute ref="{http://standards.iso.org/iso/19115/-3/gco/1.0}isoType default="mco:MD_ClassificationCode_Property""/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S100_ClassificationCode_PropertyType")
public class S100ClassificationCodePropertyType
    extends MDClassificationCodePropertyType
{

    @XmlAttribute(name = "isoType", namespace = "http://standards.iso.org/iso/19115/-3/gco/1.0")
    protected String isoType;

    /**
     * Gets the value of the isoType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsoType() {
        if (isoType == null) {
            return "mco:MD_ClassificationCode_Property";
        } else {
            return isoType;
        }
    }

    /**
     * Sets the value of the isoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsoType(String value) {
        this.isoType = value;
    }

}
