//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:27:16 PM PDT 
//


package _int.iho.s100.xc._5;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for S100_EncodingFormat.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="S100_EncodingFormat"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ISO/IEC 8211"/&gt;
 *     &lt;enumeration value="GML"/&gt;
 *     &lt;enumeration value="HDF5"/&gt;
 *     &lt;enumeration value="undefined"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "S100_EncodingFormat")
@XmlEnum
public enum S100EncodingFormat {


    /**
     * The ISO 8211 data format as defined in Part 10a
     * 
     */
    @XmlEnumValue("ISO/IEC 8211")
    ISO_IEC_8211("ISO/IEC 8211"),

    /**
     * The GML data format as defined in Part 10b
     * 
     */
    GML("GML"),

    /**
     * The HDF5 data format as defined in Part 10c
     * 
     */
    @XmlEnumValue("HDF5")
    HDF_5("HDF5"),

    /**
     * The encoding is defined in the Product Specification
     * 
     */
    @XmlEnumValue("undefined")
    UNDEFINED("undefined");
    private final String value;

    S100EncodingFormat(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static S100EncodingFormat fromValue(String v) {
        for (S100EncodingFormat c: S100EncodingFormat.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
