//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:27:16 PM PDT 
//


package _int.iho.s100.xc._5;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for S100_CompliancyCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="S100_CompliancyCategory"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="category1"/&gt;
 *     &lt;enumeration value="category2"/&gt;
 *     &lt;enumeration value="category3"/&gt;
 *     &lt;enumeration value="category4"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "S100_CompliancyCategory")
@XmlEnum
public enum S100CompliancyCategory {


    /**
     * IHO S-100 object model compliant
     * 
     */
    @XmlEnumValue("category1")
    CATEGORY_1("category1"),

    /**
     * IHO S-100 compliant with non-standard encoding
     * 
     */
    @XmlEnumValue("category2")
    CATEGORY_2("category2"),

    /**
     * IHO S-100 compliant with standard encoding
     * 
     */
    @XmlEnumValue("category3")
    CATEGORY_3("category3"),

    /**
     * IHO S-100 and IMO harmonized display compliant
     * 
     */
    @XmlEnumValue("category4")
    CATEGORY_4("category4");
    private final String value;

    S100CompliancyCategory(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static S100CompliancyCategory fromValue(String v) {
        for (S100CompliancyCategory c: S100CompliancyCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
