//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.24 at 01:44:06 PM PDT 
//


package org.iso.standards.iso._19115.__3.mcc._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import org.iso.standards.iso._19115.__3.gco._1.CodeListValueType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.iso.standards.iso._19115.__3.mcc._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AbstractMaintenanceInformation_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_MaintenanceInformation");
    private final static QName _AbstractAcquisitionInformation_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_AcquisitionInformation");
    private final static QName _AbstractApplicationSchemaInformation_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_ApplicationSchemaInformation");
    private final static QName _AbstractCitation_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_Citation");
    private final static QName _AbstractConstraints_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_Constraints");
    private final static QName _AbstractContentInformation_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_ContentInformation");
    private final static QName _AbstractDistribution_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_Distribution");
    private final static QName _AbstractExtent_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_Extent");
    private final static QName _AbstractFormat_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_Format");
    private final static QName _AbstractLineageInformation_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_LineageInformation");
    private final static QName _AbstractMetadata_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_Metadata");
    private final static QName _AbstractMetadataExtension_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_MetadataExtension");
    private final static QName _AbstractOnlineResource_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_OnlineResource");
    private final static QName _AbstractPlatform_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_Platform");
    private final static QName _AbstractPortrayalCatalogueInformation_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_PortrayalCatalogueInformation");
    private final static QName _AbstractReferenceSystem_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_ReferenceSystem");
    private final static QName _AbstractResourceDescription_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_ResourceDescription");
    private final static QName _AbstractResponsibility_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_Responsibility");
    private final static QName _AbstractSpatialRepresentation_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_SpatialRepresentation");
    private final static QName _AbstractSpatialResolution_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_SpatialResolution");
    private final static QName _AbstractStandardOrderProcess_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_StandardOrderProcess");
    private final static QName _AbstractTypedDate_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_TypedDate");
    private final static QName _AbstractParameter_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "Abstract_Parameter");
    private final static QName _MDBrowseGraphic_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "MD_BrowseGraphic");
    private final static QName _MDIdentifier_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "MD_Identifier");
    private final static QName _MDProgressCode_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "MD_ProgressCode");
    private final static QName _MDScope_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "MD_Scope");
    private final static QName _MDScopeCode_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "MD_ScopeCode");
    private final static QName _MDScopeDescription_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "MD_ScopeDescription");
    private final static QName _MDSpatialRepresentationTypeCode_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "MD_SpatialRepresentationTypeCode");
    private final static QName _URI_QNAME = new QName("http://standards.iso.org/iso/19115/-3/mcc/1.0", "URI");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.iso.standards.iso._19115.__3.mcc._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MDBrowseGraphicType }
     * 
     */
    public MDBrowseGraphicType createMDBrowseGraphicType() {
        return new MDBrowseGraphicType();
    }

    /**
     * Create an instance of {@link MDIdentifierType }
     * 
     */
    public MDIdentifierType createMDIdentifierType() {
        return new MDIdentifierType();
    }

    /**
     * Create an instance of {@link MDScopeType }
     * 
     */
    public MDScopeType createMDScopeType() {
        return new MDScopeType();
    }

    /**
     * Create an instance of {@link MDScopeDescriptionType }
     * 
     */
    public MDScopeDescriptionType createMDScopeDescriptionType() {
        return new MDScopeDescriptionType();
    }

    /**
     * Create an instance of {@link URIType }
     * 
     */
    public URIType createURIType() {
        return new URIType();
    }

    /**
     * Create an instance of {@link AbstractAcquisitionInformationPropertyType }
     * 
     */
    public AbstractAcquisitionInformationPropertyType createAbstractAcquisitionInformationPropertyType() {
        return new AbstractAcquisitionInformationPropertyType();
    }

    /**
     * Create an instance of {@link AbstractApplicationSchemaInformationPropertyType }
     * 
     */
    public AbstractApplicationSchemaInformationPropertyType createAbstractApplicationSchemaInformationPropertyType() {
        return new AbstractApplicationSchemaInformationPropertyType();
    }

    /**
     * Create an instance of {@link AbstractCitationPropertyType }
     * 
     */
    public AbstractCitationPropertyType createAbstractCitationPropertyType() {
        return new AbstractCitationPropertyType();
    }

    /**
     * Create an instance of {@link AbstractConstraintsPropertyType }
     * 
     */
    public AbstractConstraintsPropertyType createAbstractConstraintsPropertyType() {
        return new AbstractConstraintsPropertyType();
    }

    /**
     * Create an instance of {@link AbstractContentInformationPropertyType }
     * 
     */
    public AbstractContentInformationPropertyType createAbstractContentInformationPropertyType() {
        return new AbstractContentInformationPropertyType();
    }

    /**
     * Create an instance of {@link AbstractDistributionPropertyType }
     * 
     */
    public AbstractDistributionPropertyType createAbstractDistributionPropertyType() {
        return new AbstractDistributionPropertyType();
    }

    /**
     * Create an instance of {@link AbstractExtentPropertyType }
     * 
     */
    public AbstractExtentPropertyType createAbstractExtentPropertyType() {
        return new AbstractExtentPropertyType();
    }

    /**
     * Create an instance of {@link AbstractFormatPropertyType }
     * 
     */
    public AbstractFormatPropertyType createAbstractFormatPropertyType() {
        return new AbstractFormatPropertyType();
    }

    /**
     * Create an instance of {@link AbstractLineageInformationPropertyType }
     * 
     */
    public AbstractLineageInformationPropertyType createAbstractLineageInformationPropertyType() {
        return new AbstractLineageInformationPropertyType();
    }

    /**
     * Create an instance of {@link AbstractMaintenanceInformationPropertyType }
     * 
     */
    public AbstractMaintenanceInformationPropertyType createAbstractMaintenanceInformationPropertyType() {
        return new AbstractMaintenanceInformationPropertyType();
    }

    /**
     * Create an instance of {@link AbstractMetadataPropertyType }
     * 
     */
    public AbstractMetadataPropertyType createAbstractMetadataPropertyType() {
        return new AbstractMetadataPropertyType();
    }

    /**
     * Create an instance of {@link AbstractMetadataExtensionPropertyType }
     * 
     */
    public AbstractMetadataExtensionPropertyType createAbstractMetadataExtensionPropertyType() {
        return new AbstractMetadataExtensionPropertyType();
    }

    /**
     * Create an instance of {@link AbstractOnlineResourcePropertyType }
     * 
     */
    public AbstractOnlineResourcePropertyType createAbstractOnlineResourcePropertyType() {
        return new AbstractOnlineResourcePropertyType();
    }

    /**
     * Create an instance of {@link AbstractPlatformPropertyType }
     * 
     */
    public AbstractPlatformPropertyType createAbstractPlatformPropertyType() {
        return new AbstractPlatformPropertyType();
    }

    /**
     * Create an instance of {@link AbstractPortrayalCatalogueInformationPropertyType }
     * 
     */
    public AbstractPortrayalCatalogueInformationPropertyType createAbstractPortrayalCatalogueInformationPropertyType() {
        return new AbstractPortrayalCatalogueInformationPropertyType();
    }

    /**
     * Create an instance of {@link AbstractReferenceSystemPropertyType }
     * 
     */
    public AbstractReferenceSystemPropertyType createAbstractReferenceSystemPropertyType() {
        return new AbstractReferenceSystemPropertyType();
    }

    /**
     * Create an instance of {@link AbstractResourceDescriptionPropertyType }
     * 
     */
    public AbstractResourceDescriptionPropertyType createAbstractResourceDescriptionPropertyType() {
        return new AbstractResourceDescriptionPropertyType();
    }

    /**
     * Create an instance of {@link AbstractResponsibilityPropertyType }
     * 
     */
    public AbstractResponsibilityPropertyType createAbstractResponsibilityPropertyType() {
        return new AbstractResponsibilityPropertyType();
    }

    /**
     * Create an instance of {@link AbstractSpatialRepresentationPropertyType }
     * 
     */
    public AbstractSpatialRepresentationPropertyType createAbstractSpatialRepresentationPropertyType() {
        return new AbstractSpatialRepresentationPropertyType();
    }

    /**
     * Create an instance of {@link AbstractSpatialResolutionPropertyType }
     * 
     */
    public AbstractSpatialResolutionPropertyType createAbstractSpatialResolutionPropertyType() {
        return new AbstractSpatialResolutionPropertyType();
    }

    /**
     * Create an instance of {@link AbstractStandardOrderProcessPropertyType }
     * 
     */
    public AbstractStandardOrderProcessPropertyType createAbstractStandardOrderProcessPropertyType() {
        return new AbstractStandardOrderProcessPropertyType();
    }

    /**
     * Create an instance of {@link AbstractTypedDatePropertyType }
     * 
     */
    public AbstractTypedDatePropertyType createAbstractTypedDatePropertyType() {
        return new AbstractTypedDatePropertyType();
    }

    /**
     * Create an instance of {@link AbstractParameterPropertyType }
     * 
     */
    public AbstractParameterPropertyType createAbstractParameterPropertyType() {
        return new AbstractParameterPropertyType();
    }

    /**
     * Create an instance of {@link MDBrowseGraphicPropertyType }
     * 
     */
    public MDBrowseGraphicPropertyType createMDBrowseGraphicPropertyType() {
        return new MDBrowseGraphicPropertyType();
    }

    /**
     * Create an instance of {@link MDIdentifierPropertyType }
     * 
     */
    public MDIdentifierPropertyType createMDIdentifierPropertyType() {
        return new MDIdentifierPropertyType();
    }

    /**
     * Create an instance of {@link MDProgressCodePropertyType }
     * 
     */
    public MDProgressCodePropertyType createMDProgressCodePropertyType() {
        return new MDProgressCodePropertyType();
    }

    /**
     * Create an instance of {@link MDScopePropertyType }
     * 
     */
    public MDScopePropertyType createMDScopePropertyType() {
        return new MDScopePropertyType();
    }

    /**
     * Create an instance of {@link MDScopeCodePropertyType }
     * 
     */
    public MDScopeCodePropertyType createMDScopeCodePropertyType() {
        return new MDScopeCodePropertyType();
    }

    /**
     * Create an instance of {@link MDScopeDescriptionPropertyType }
     * 
     */
    public MDScopeDescriptionPropertyType createMDScopeDescriptionPropertyType() {
        return new MDScopeDescriptionPropertyType();
    }

    /**
     * Create an instance of {@link MDSpatialRepresentationTypeCodePropertyType }
     * 
     */
    public MDSpatialRepresentationTypeCodePropertyType createMDSpatialRepresentationTypeCodePropertyType() {
        return new MDSpatialRepresentationTypeCodePropertyType();
    }

    /**
     * Create an instance of {@link URIPropertyType }
     * 
     */
    public URIPropertyType createURIPropertyType() {
        return new URIPropertyType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractMaintenanceInformationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractMaintenanceInformationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_MaintenanceInformation", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractMaintenanceInformationType> createAbstractMaintenanceInformation(AbstractMaintenanceInformationType value) {
        return new JAXBElement<AbstractMaintenanceInformationType>(_AbstractMaintenanceInformation_QNAME, AbstractMaintenanceInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractAcquisitionInformationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractAcquisitionInformationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_AcquisitionInformation", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractAcquisitionInformationType> createAbstractAcquisitionInformation(AbstractAcquisitionInformationType value) {
        return new JAXBElement<AbstractAcquisitionInformationType>(_AbstractAcquisitionInformation_QNAME, AbstractAcquisitionInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractApplicationSchemaInformationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractApplicationSchemaInformationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_ApplicationSchemaInformation", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractApplicationSchemaInformationType> createAbstractApplicationSchemaInformation(AbstractApplicationSchemaInformationType value) {
        return new JAXBElement<AbstractApplicationSchemaInformationType>(_AbstractApplicationSchemaInformation_QNAME, AbstractApplicationSchemaInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractCitationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractCitationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_Citation", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractCitationType> createAbstractCitation(AbstractCitationType value) {
        return new JAXBElement<AbstractCitationType>(_AbstractCitation_QNAME, AbstractCitationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractConstraintsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractConstraintsType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_Constraints", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractConstraintsType> createAbstractConstraints(AbstractConstraintsType value) {
        return new JAXBElement<AbstractConstraintsType>(_AbstractConstraints_QNAME, AbstractConstraintsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractContentInformationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractContentInformationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_ContentInformation", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractContentInformationType> createAbstractContentInformation(AbstractContentInformationType value) {
        return new JAXBElement<AbstractContentInformationType>(_AbstractContentInformation_QNAME, AbstractContentInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractDistributionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractDistributionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_Distribution", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractDistributionType> createAbstractDistribution(AbstractDistributionType value) {
        return new JAXBElement<AbstractDistributionType>(_AbstractDistribution_QNAME, AbstractDistributionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractExtentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractExtentType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_Extent", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractExtentType> createAbstractExtent(AbstractExtentType value) {
        return new JAXBElement<AbstractExtentType>(_AbstractExtent_QNAME, AbstractExtentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractFormatType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractFormatType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_Format", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractFormatType> createAbstractFormat(AbstractFormatType value) {
        return new JAXBElement<AbstractFormatType>(_AbstractFormat_QNAME, AbstractFormatType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractLineageInformationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractLineageInformationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_LineageInformation", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractLineageInformationType> createAbstractLineageInformation(AbstractLineageInformationType value) {
        return new JAXBElement<AbstractLineageInformationType>(_AbstractLineageInformation_QNAME, AbstractLineageInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractMetadataType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractMetadataType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_Metadata", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractMetadataType> createAbstractMetadata(AbstractMetadataType value) {
        return new JAXBElement<AbstractMetadataType>(_AbstractMetadata_QNAME, AbstractMetadataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractMetadataExtensionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractMetadataExtensionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_MetadataExtension", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractMetadataExtensionType> createAbstractMetadataExtension(AbstractMetadataExtensionType value) {
        return new JAXBElement<AbstractMetadataExtensionType>(_AbstractMetadataExtension_QNAME, AbstractMetadataExtensionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractOnlineResourceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractOnlineResourceType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_OnlineResource", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractOnlineResourceType> createAbstractOnlineResource(AbstractOnlineResourceType value) {
        return new JAXBElement<AbstractOnlineResourceType>(_AbstractOnlineResource_QNAME, AbstractOnlineResourceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractPlatformType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractPlatformType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_Platform", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractPlatformType> createAbstractPlatform(AbstractPlatformType value) {
        return new JAXBElement<AbstractPlatformType>(_AbstractPlatform_QNAME, AbstractPlatformType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractPortrayalCatalogueInformationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractPortrayalCatalogueInformationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_PortrayalCatalogueInformation", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractPortrayalCatalogueInformationType> createAbstractPortrayalCatalogueInformation(AbstractPortrayalCatalogueInformationType value) {
        return new JAXBElement<AbstractPortrayalCatalogueInformationType>(_AbstractPortrayalCatalogueInformation_QNAME, AbstractPortrayalCatalogueInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractReferenceSystemType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractReferenceSystemType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_ReferenceSystem", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractReferenceSystemType> createAbstractReferenceSystem(AbstractReferenceSystemType value) {
        return new JAXBElement<AbstractReferenceSystemType>(_AbstractReferenceSystem_QNAME, AbstractReferenceSystemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractResourceDescriptionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractResourceDescriptionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_ResourceDescription", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractResourceDescriptionType> createAbstractResourceDescription(AbstractResourceDescriptionType value) {
        return new JAXBElement<AbstractResourceDescriptionType>(_AbstractResourceDescription_QNAME, AbstractResourceDescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractResponsibilityType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractResponsibilityType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_Responsibility", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractResponsibilityType> createAbstractResponsibility(AbstractResponsibilityType value) {
        return new JAXBElement<AbstractResponsibilityType>(_AbstractResponsibility_QNAME, AbstractResponsibilityType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractSpatialRepresentationType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractSpatialRepresentationType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_SpatialRepresentation", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractSpatialRepresentationType> createAbstractSpatialRepresentation(AbstractSpatialRepresentationType value) {
        return new JAXBElement<AbstractSpatialRepresentationType>(_AbstractSpatialRepresentation_QNAME, AbstractSpatialRepresentationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractSpatialResolutionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractSpatialResolutionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_SpatialResolution", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractSpatialResolutionType> createAbstractSpatialResolution(AbstractSpatialResolutionType value) {
        return new JAXBElement<AbstractSpatialResolutionType>(_AbstractSpatialResolution_QNAME, AbstractSpatialResolutionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractStandardOrderProcessType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractStandardOrderProcessType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_StandardOrderProcess", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractStandardOrderProcessType> createAbstractStandardOrderProcess(AbstractStandardOrderProcessType value) {
        return new JAXBElement<AbstractStandardOrderProcessType>(_AbstractStandardOrderProcess_QNAME, AbstractStandardOrderProcessType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractTypedDateType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractTypedDateType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_TypedDate", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractTypedDateType> createAbstractTypedDate(AbstractTypedDateType value) {
        return new JAXBElement<AbstractTypedDateType>(_AbstractTypedDate_QNAME, AbstractTypedDateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractParameterType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AbstractParameterType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "Abstract_Parameter", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractParameterType> createAbstractParameter(AbstractParameterType value) {
        return new JAXBElement<AbstractParameterType>(_AbstractParameter_QNAME, AbstractParameterType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MDBrowseGraphicType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MDBrowseGraphicType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "MD_BrowseGraphic", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<MDBrowseGraphicType> createMDBrowseGraphic(MDBrowseGraphicType value) {
        return new JAXBElement<MDBrowseGraphicType>(_MDBrowseGraphic_QNAME, MDBrowseGraphicType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MDIdentifierType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MDIdentifierType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "MD_Identifier", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<MDIdentifierType> createMDIdentifier(MDIdentifierType value) {
        return new JAXBElement<MDIdentifierType>(_MDIdentifier_QNAME, MDIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeListValueType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CodeListValueType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "MD_ProgressCode", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "CharacterString")
    public JAXBElement<CodeListValueType> createMDProgressCode(CodeListValueType value) {
        return new JAXBElement<CodeListValueType>(_MDProgressCode_QNAME, CodeListValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MDScopeType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MDScopeType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "MD_Scope", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<MDScopeType> createMDScope(MDScopeType value) {
        return new JAXBElement<MDScopeType>(_MDScope_QNAME, MDScopeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeListValueType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CodeListValueType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "MD_ScopeCode", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "CharacterString")
    public JAXBElement<CodeListValueType> createMDScopeCode(CodeListValueType value) {
        return new JAXBElement<CodeListValueType>(_MDScopeCode_QNAME, CodeListValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MDScopeDescriptionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MDScopeDescriptionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "MD_ScopeDescription", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<MDScopeDescriptionType> createMDScopeDescription(MDScopeDescriptionType value) {
        return new JAXBElement<MDScopeDescriptionType>(_MDScopeDescription_QNAME, MDScopeDescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeListValueType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CodeListValueType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "MD_SpatialRepresentationTypeCode", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "CharacterString")
    public JAXBElement<CodeListValueType> createMDSpatialRepresentationTypeCode(CodeListValueType value) {
        return new JAXBElement<CodeListValueType>(_MDSpatialRepresentationTypeCode_QNAME, CodeListValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link URIType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link URIType }{@code >}
     */
    @XmlElementDecl(namespace = "http://standards.iso.org/iso/19115/-3/mcc/1.0", name = "URI", substitutionHeadNamespace = "http://standards.iso.org/iso/19115/-3/gco/1.0", substitutionHeadName = "AbstractObject")
    public JAXBElement<URIType> createURI(URIType value) {
        return new JAXBElement<URIType>(_URI_QNAME, URIType.class, null, value);
    }

}
