//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.24 at 02:20:02 PM PDT 
//


package _int.iho.s100.xc._5;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for S100_NavigationPurpose.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="S100_NavigationPurpose"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="port"/&gt;
 *     &lt;enumeration value="transit"/&gt;
 *     &lt;enumeration value="overview"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "S100_NavigationPurpose")
@XmlEnum
public enum S100NavigationPurpose {


    /**
     * For port and near shore operations
     * 
     */
    @XmlEnumValue("port")
    PORT("port"),

    /**
     * For coast and planning purposes
     * 
     */
    @XmlEnumValue("transit")
    TRANSIT("transit"),

    /**
     * For ocean crossing and planning purposes
     * 
     */
    @XmlEnumValue("overview")
    OVERVIEW("overview");
    private final String value;

    S100NavigationPurpose(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static S100NavigationPurpose fromValue(String v) {
        for (S100NavigationPurpose c: S100NavigationPurpose.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
