//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.24 at 02:21:01 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.iho.int/s100/se/5.2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package _int.iho.s100.se._5;
