//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.25 at 04:24:11 PM PDT 
//


package _int.iho.s100gml._5;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import net.opengis.gml._3.DirectPositionType;
import net.opengis.gml._3.PointPropertyType;


/**
 * Defintion of the Vector datatype used in splines
 * 
 * <p>Java class for VectorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VectorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="origin"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element ref="{http://www.opengis.net/gml/3.2}pos"/&gt;
 *                   &lt;element ref="{http://www.opengis.net/gml/3.2}pointProperty"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dimension" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/&gt;
 *         &lt;element name="offset" type="{http://www.opengis.net/gml/3.2}doubleList"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VectorType", propOrder = {
    "origin",
    "dimension",
    "offset"
})
public class VectorType {

    @XmlElement(required = true)
    protected VectorType.Origin origin;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger dimension;
    @XmlList
    @XmlElement(type = Double.class)
    protected List<Double> offset;

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link VectorType.Origin }
     *     
     */
    public VectorType.Origin getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link VectorType.Origin }
     *     
     */
    public void setOrigin(VectorType.Origin value) {
        this.origin = value;
    }

    /**
     * Gets the value of the dimension property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDimension() {
        return dimension;
    }

    /**
     * Sets the value of the dimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDimension(BigInteger value) {
        this.dimension = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOffset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     * 
     * 
     */
    public List<Double> getOffset() {
        if (offset == null) {
            offset = new ArrayList<Double>();
        }
        return this.offset;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element ref="{http://www.opengis.net/gml/3.2}pos"/&gt;
     *         &lt;element ref="{http://www.opengis.net/gml/3.2}pointProperty"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pos",
        "pointProperty"
    })
    public static class Origin {

        @XmlElement(namespace = "http://www.opengis.net/gml/3.2")
        protected DirectPositionType pos;
        @XmlElement(namespace = "http://www.opengis.net/gml/3.2")
        protected PointPropertyType pointProperty;

        /**
         * Gets the value of the pos property.
         * 
         * @return
         *     possible object is
         *     {@link DirectPositionType }
         *     
         */
        public DirectPositionType getPos() {
            return pos;
        }

        /**
         * Sets the value of the pos property.
         * 
         * @param value
         *     allowed object is
         *     {@link DirectPositionType }
         *     
         */
        public void setPos(DirectPositionType value) {
            this.pos = value;
        }

        /**
         * Gets the value of the pointProperty property.
         * 
         * @return
         *     possible object is
         *     {@link PointPropertyType }
         *     
         */
        public PointPropertyType getPointProperty() {
            return pointProperty;
        }

        /**
         * Sets the value of the pointProperty property.
         * 
         * @param value
         *     allowed object is
         *     {@link PointPropertyType }
         *     
         */
        public void setPointProperty(PointPropertyType value) {
            this.pointProperty = value;
        }

    }

}
